#!/usr/bin/env bash
# Backup groups: one restic repository per project, plus "system". Pure
# logic: no root, no restic, no Docker. Covered by tests/backup.bats.
#
# A group <name> consists of:
#   ${BACKUP_CONF_DIR}/<name>.env        repository, retention, ping (600)
#   ${BACKUP_CONF_DIR}/<name>.password   repository password, generated (600)
#   ${HOOKS_DIR}/<name>/*.sh             hooks of the project (not for system)
#   ${STAGING_DIR}/<name>/               dumps written by the hooks
#   ${BACKUP_REPO_ROOT}/<name>/          default (local) repository
#
# Requires lib/common.sh.

if [[ -n "${VPS_STACK_BACKUP_LOADED:-}" ]]; then
    return 0
fi
VPS_STACK_BACKUP_LOADED=1

BACKUP_SYSTEM_GROUP="system"

# validate_backup_group <name>: the name of a project directory in /srv, or
# "system".
validate_backup_group() {
    local LC_ALL=C
    local re='^[a-z0-9][a-z0-9_-]{0,62}$'
    if [[ ! "${1:-}" =~ ${re} ]]; then
        printf 'Invalid value: the backup group must be a project name (a-z, 0-9, _ and -, up to 63 characters) or "system".\n' >&2
        return 1
    fi
}

backup_group_conf() { printf '%s/%s.env\n' "${BACKUP_CONF_DIR}" "$1"; }
backup_group_password() { printf '%s/%s.password\n' "${BACKUP_CONF_DIR}" "$1"; }
backup_group_hooks() { printf '%s/%s\n' "${HOOKS_DIR}" "$1"; }
backup_group_staging() { printf '%s/%s\n' "${STAGING_DIR}" "$1"; }
backup_group_default_repo() { printf '%s/%s\n' "${BACKUP_REPO_ROOT}" "$1"; }

# backup_groups: print the configured groups, "system" first, then the
# projects in alphabetical order.
backup_groups() {
    local file name
    local -a projects=()
    [[ -d "${BACKUP_CONF_DIR}" ]] || return 0
    for file in "${BACKUP_CONF_DIR}"/*.env; do
        [[ -f "${file}" ]] || continue
        name="$(basename "${file}" .env)"
        validate_backup_group "${name}" 2>/dev/null || continue
        if [[ "${name}" == "${BACKUP_SYSTEM_GROUP}" ]]; then
            printf '%s\n' "${name}"
        else
            projects+=("${name}")
        fi
    done
    if [[ "${#projects[@]}" -gt 0 ]]; then
        printf '%s\n' "${projects[@]}" | LC_ALL=C sort
    fi
}

# backup_repo_is_local <repository>: a path on this server ("/..." or
# "local:/..."), as opposed to s3:, sftp:, rest: and the other backends.
backup_repo_is_local() {
    case "$1" in
        /* | local:/*) return 0 ;;
        *) return 1 ;;
    esac
}

# backup_last_ok <group> <log file...>: print the timestamp of the newest
# "<timestamp> BACKUP_OK <group>" line. Files are read in the order given,
# oldest first, so the newest entry wins. Unreadable files are skipped.
backup_last_ok() {
    local group="$1" file candidate last=""
    shift
    for file in "$@"; do
        [[ -r "${file}" ]] || continue
        candidate="$(awk -v group="${group}" '$2 == "BACKUP_OK" && $3 == group && NF == 3 { ts = $1 } END { print ts }' "${file}")"
        [[ -n "${candidate}" ]] && last="${candidate}"
    done
    printf '%s\n' "${last}"
}

# backup_target_ok <directory>: a restore never writes over live data. The
# target is an absolute path that does not exist yet or is an empty
# directory.
backup_target_ok() {
    local target="${1:-}"
    if [[ "${target}" != /* || "${target}" == "/" ]]; then
        printf 'Invalid value: the target must be an absolute path to a new or empty directory, e.g. /tmp/restore-example-app.\n' >&2
        return 1
    fi
    if [[ -e "${target}" ]]; then
        if [[ ! -d "${target}" || -n "$(ls -A "${target}" 2>/dev/null)" ]]; then
            printf 'Invalid value: %s exists and is not an empty directory. A restore never writes over existing data.\n' "${target}" >&2
            return 1
        fi
    fi
}

# backup_export_format <file>: the archive format named by the extension.
backup_export_format() {
    case "${1:-}" in
        /*.tar) printf 'tar\n' ;;
        /*.zip) printf 'zip\n' ;;
        *)
            printf 'Invalid value: the output must be an absolute path ending in .tar or .zip.\n' >&2
            return 1
            ;;
    esac
}

# backup_prune_staging <directory> <keep>: in every subdirectory (one per
# hook), keep the <keep> newest files and print the paths of the others.
# Prints only; the caller removes them, so --dry-run stays in one place.
backup_prune_staging() {
    local dir="$1" keep="$2" sub file count
    [[ -d "${dir}" ]] || return 0
    for sub in "${dir}"/*/; do
        [[ -d "${sub}" ]] || continue
        count=0
        # shellcheck disable=SC2012  # dump names are generated by hooks; newest-first order is what matters
        while IFS= read -r file; do
            [[ -f "${sub}${file}" ]] || continue
            count=$((count + 1))
            if [[ "${count}" -gt "${keep}" ]]; then
                printf '%s\n' "${sub}${file}"
            fi
        done < <(ls -1t "${sub}" 2>/dev/null)
    done
}
