#!/usr/bin/env bash
# Off-site backup with restic: project dumps (hooks), certificates and the
# local configuration. See docs/backup-restore.md.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

LOCK_FILE="${VPS_STACK_BACKUP_LOCK:-/run/lock/vps-stack-backup.lock}"
CRON_FILE="/etc/cron.d/vps-stack-backup"
FAILURES=()

usage() {
    cat <<USAGE
Usage: sudo vps-stack backup <command> [--dry-run]

Commands:
  init    initialise the restic repository (only when it does not exist yet)
  run     run a backup: project hooks, restic backup, retention
  setup   install the cron job (every 6 hours)

Configuration: ${RESTIC_ENV_FILE} (see config/restic.env.example)
Repository password: ${RESTIC_PASSWORD_DEFAULT_FILE}
Log: ${BACKUP_LOG_FILE}

Keep the repository password in a password manager as well. Without it the
backup is useless, and on purpose it is NOT part of the backup itself.
USAGE
}

stamp() { date -u +%Y-%m-%dT%H:%M:%SZ; }

note() { printf '%s %s\n' "$(stamp)" "$*"; }

load_restic_config() {
    [[ -f "${RESTIC_ENV_FILE}" ]] ||
        die "${RESTIC_ENV_FILE} not found. Copy config/restic.env.example, fill it in and chmod 600 it."
    file_has_mode "${RESTIC_ENV_FILE}" 600 ||
        die "${RESTIC_ENV_FILE} must have mode 600 (it holds credentials). Fix: chmod 600 ${RESTIC_ENV_FILE}"
    load_env_file "${RESTIC_ENV_FILE}" export
    [[ -n "${RESTIC_REPOSITORY:-}" ]] || die "RESTIC_REPOSITORY in ${RESTIC_ENV_FILE} is empty."

    if [[ -z "${RESTIC_PASSWORD_FILE:-}" && -z "${RESTIC_PASSWORD_COMMAND:-}" && -z "${RESTIC_PASSWORD:-}" ]]; then
        export RESTIC_PASSWORD_FILE="${RESTIC_PASSWORD_DEFAULT_FILE}"
    fi
    if [[ -n "${RESTIC_PASSWORD_FILE:-}" ]]; then
        [[ -s "${RESTIC_PASSWORD_FILE}" ]] ||
            die "Repository password file not found: ${RESTIC_PASSWORD_FILE}. Create it (chmod 600) and ALSO save the password in a password manager."
        file_has_mode "${RESTIC_PASSWORD_FILE}" 600 ||
            die "${RESTIC_PASSWORD_FILE} must have mode 600."
    fi
    require_cmd restic
}

# hc_ping <suffix>: healthchecks.io style ping; silent no-op without HC_URL.
hc_ping() {
    [[ -n "${HC_URL:-}" ]] || return 0
    is_dry_run && {
        log_dry "ping ${HC_URL}$1"
        return 0
    }
    curl -fsS -m 10 --retry 3 -o /dev/null "${HC_URL}$1" || note "WARN: monitoring ping failed"
}

cmd_init() {
    load_restic_config
    if restic cat config >/dev/null 2>&1; then
        log_ok "The repository already exists and the password matches. Nothing to do."
        return 0
    fi
    # `restic init` itself refuses to touch a repository that already exists,
    # so a wrong password or a network error cannot overwrite anything.
    run restic init
    log_ok "Repository initialised."
    log_warn "Save the repository password in a password manager. Without it the backup can NOT be restored."
}

cmd_setup() {
    local content
    load_restic_config
    content="$(render_template "${REPO_ROOT}/templates/cron-backup.tmpl" \
        "VPS_STACK_BIN=${REPO_ROOT}/bin/vps-stack")"
    write_file "${CRON_FILE}" 644 <<<"${content}"
    log_ok "The backup will run every 6 hours (${CRON_FILE})."
    log_info "Run the first backup by hand and check the result: sudo vps-stack backup run"
}

run_hooks() {
    local hook name
    for hook in "${HOOKS_DIR}"/*.sh; do
        [[ -f "${hook}" && -x "${hook}" ]] || continue
        name="$(basename "${hook}" .sh)"
        note "hook ${name}: start"
        run install -d -m 700 "${STAGING_DIR}/${name}"
        # A failing hook must not stop the others or the backup itself, but
        # the whole run is reported as failed.
        if STAGING_DIR="${STAGING_DIR}" HOOK_NAME="${name}" HOOK_EXTRA_PATHS_FILE="${EXTRA_PATHS_FILE}" \
            run "${hook}"; then
            note "hook ${name}: OK"
        else
            note "hook ${name}: ERROR"
            FAILURES+=("hook ${name}")
        fi
    done
}

# prune_staging: keep the two newest dumps of every hook.
prune_staging() {
    local dir file count
    for dir in "${STAGING_DIR}"/*/; do
        [[ -d "${dir}" ]] || continue
        count=0
        # shellcheck disable=SC2012  # dump names are generated by hooks; newest-first order is what matters
        while IFS= read -r file; do
            count=$((count + 1))
            if [[ "${count}" -gt 2 && -f "${dir}${file}" ]]; then
                run rm -f "${dir}${file}"
            fi
        done < <(ls -1t "${dir}" 2>/dev/null)
    done
}

cmd_run() {
    local code=0 path
    local -a paths=() restic_args=()

    load_restic_config
    require_cmd flock

    if ! is_dry_run; then
        exec 9>"${LOCK_FILE}"
        flock -n 9 || die "Another backup is in progress (${LOCK_FILE})."
        touch "${BACKUP_LOG_FILE}"
        chmod 600 "${BACKUP_LOG_FILE}"
        exec > >(tee -a "${BACKUP_LOG_FILE}") 2>&1
    fi

    note "backup: start"
    hc_ping "/start"

    EXTRA_PATHS_FILE="$(mktemp)"
    trap 'rm -f "${EXTRA_PATHS_FILE}"' EXIT
    run install -d -m 700 "${STAGING_DIR}"
    run_hooks

    for path in "${STAGING_DIR}" "${CADDY_DATA_DIR}/data" "${ETC_DIR}" /srv/*/.env; do
        [[ -e "${path}" ]] && paths+=("${path}")
    done
    while IFS= read -r path || [[ -n "${path}" ]]; do
        [[ -n "${path}" ]] || continue
        if [[ "${path}" == /* && -e "${path}" ]]; then
            paths+=("${path}")
        else
            note "WARN: path from a hook does not exist or is not absolute: ${path}"
            FAILURES+=("path ${path}")
        fi
    done <"${EXTRA_PATHS_FILE}"

    # Repository credentials never go into the repository they unlock.
    restic_args=(backup --tag vps-stack --exclude "${ETC_DIR}/restic*")
    if [[ "${#paths[@]}" -eq 0 ]]; then
        note "ERROR: nothing to back up"
        FAILURES+=("no paths")
    else
        run restic "${restic_args[@]}" "${paths[@]}" || code=$?
        case "${code}" in
            0) note "restic backup: OK" ;;
            3)
                note "restic backup: some files could not be read"
                FAILURES+=("restic backup (incomplete)")
                ;;
            *)
                note "restic backup: ERROR (exit code ${code})"
                FAILURES+=("restic backup")
                ;;
        esac
    fi

    if [[ "${code}" == "0" || "${code}" == "3" ]]; then
        run restic forget --tag vps-stack --group-by host \
            --keep-daily 14 --keep-weekly 8 --keep-monthly 6 || FAILURES+=("restic forget")
        # Weekly maintenance: the first run on Sunday (UTC).
        if [[ "$(date -u +%u)" == "7" && "$((10#$(date -u +%H)))" -lt 6 ]]; then
            run restic prune || FAILURES+=("restic prune")
            run restic check --read-data-subset=5% || FAILURES+=("restic check")
        fi
    fi

    prune_staging

    if [[ "${#FAILURES[@]}" -gt 0 ]]; then
        note "backup: ERROR (${FAILURES[*]})"
        hc_ping "/fail"
        exit 1
    fi
    if is_dry_run; then
        note "backup: dry-run finished"
    else
        # verify.sh looks for this exact marker.
        note "BACKUP_OK"
    fi
    hc_ping ""
}

main() {
    local command=""
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --dry-run) DRY_RUN=1 ;;
            -h | --help | help)
                usage
                exit 0
                ;;
            init | run | setup)
                [[ -z "${command}" ]] || die "Give exactly one command."
                command="$1"
                ;;
            *)
                usage >&2
                die "Unknown argument: $1"
                ;;
        esac
        shift
    done
    [[ -n "${command}" ]] || {
        usage
        exit 0
    }
    require_root
    case "${command}" in
        init) cmd_init ;;
        run) cmd_run ;;
        setup) cmd_setup ;;
        *) ;;
    esac
}

main "$@"
