#!/usr/bin/env bash
# List the sites configured in /etc/vps-stack/sites. Read-only.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

usage() {
    cat <<USAGE
Usage: vps-stack list-sites

Prints a table: domain, upstream, aliases, redirects and whether the upstream
container is running.
USAGE
}

# parse_site <file>: sets SITE_DOMAIN, SITE_ALIASES, SITE_UPSTREAM and
# SITE_REDIRECTS from a file generated by add-site.
parse_site() {
    local file="$1" line hosts in_redirect_block=0 pending_hosts=""
    SITE_DOMAIN=""
    SITE_ALIASES=""
    SITE_UPSTREAM=""
    SITE_REDIRECTS=""
    while IFS= read -r line; do
        case "${line}" in
            "" | "#"* | "}"*) continue ;;
            " "*)
                line="${line#"${line%%[![:space:]]*}"}"
                case "${line}" in
                    "reverse_proxy "*) SITE_UPSTREAM="${line#reverse_proxy }" ;;
                    "redir "*) in_redirect_block=1 ;;
                    *) ;;
                esac
                if [[ "${in_redirect_block}" == "1" && -n "${pending_hosts}" ]]; then
                    SITE_REDIRECTS="${SITE_REDIRECTS:+${SITE_REDIRECTS},}${pending_hosts}"
                    pending_hosts=""
                    in_redirect_block=0
                fi
                ;;
            *"{")
                hosts="$(printf '%s' "${line% \{}" | tr -d ' ')"
                if [[ -z "${SITE_DOMAIN}" ]]; then
                    SITE_DOMAIN="${hosts%%,*}"
                    if [[ "${hosts}" == *,* ]]; then
                        SITE_ALIASES="${hosts#*,}"
                    fi
                else
                    pending_hosts="${hosts}"
                fi
                ;;
            *) ;;
        esac
    done <"${file}"
}

main() {
    case "${1:-}" in
        -h | --help)
            usage
            exit 0
            ;;
        "") ;;
        *)
            usage >&2
            exit 2
            ;;
    esac
    require_etc_access read

    local file running="" state count=0
    if have_cmd docker; then
        running="$(docker ps --format '{{.Names}}' 2>/dev/null || true)"
    fi

    printf '%s%-32s %-28s %-10s %-28s %s%s\n' "${C_BOLD}" "DOMAIN" "UPSTREAM" "CONTAINER" "ALIASES" "REDIRECTS" "${C_RESET}"
    for file in "${SITES_DIR}"/*.caddy; do
        [[ -f "${file}" ]] || continue
        parse_site "${file}"
        if [[ "${file}" == "${MONITOR_SITE_FILE}" ]]; then
            printf '%-32s %-28s %-10s %-28s %s\n' "${SITE_DOMAIN:-?}" "(status page)" "-" "-" "-"
            count=$((count + 1))
            continue
        fi
        if [[ -z "${running}" ]]; then
            state="?"
        elif grep -qxF -- "${SITE_UPSTREAM%%:*}" <<<"${running}"; then
            state="running"
        else
            state="MISSING"
        fi
        printf '%-32s %-28s %-10s %-28s %s\n' "${SITE_DOMAIN:-?}" "${SITE_UPSTREAM:-?}" "${state}" \
            "${SITE_ALIASES:--}" "${SITE_REDIRECTS:--}"
        count=$((count + 1))
    done
    if [[ "${count}" -eq 0 ]]; then
        log_info "(no sites; add the first one: vps-stack add-site <domain> <upstream>)"
    fi
}

main "$@"
